version: '3.8'
 
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=somerootpass
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=dockerizeme_db
            - MYSQL_USER=admin
    web:
        build: .
        ports:
            - 8080:80